### ISSUE TITLE
Randomization is currently inoperable when run from installed version.

### ISSUE THREAD

**Issue by LaneDibello** [LaneDibello/Kotor-Randomizer-2#28]
After rebuilding the installer and installing the randomizer and a second machine, I've discovered that there are some serious issues  with multiple features.

- [x] The module form cannot be opened due to lack of the Xml directory and module XML file. This can easily be solved by including these in the installer as they should have been. (I'll be pushing a fix for this soon)
- [x] An exception is thrown whenever attempting the open the spoiler folder for the first time. It is worth mentioning that there are no spoiler logs included within the folder yet, however usually selecting this option would create such a folder. I believe the access denied exceptions we're getting is a result of not being able to create the Spoiler folder in the Current Directory.  
- [x]  Unable to randomize as "current.krp" is not available. It would appear that the authority for creating this file is not available for the directory that the program is installed in ("Program Files (x86)" by default)

**Comment by LaneDibello** [comment]
The Exception thrown for creating current.krp:
```
************** Exception Text **************
System.UnauthorizedAccessException: Access to the path 'C:\Program Files (x86)\Kotor Speedrun Community\Kotor Randomizer\current.krp' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.File.OpenWrite(String path)
   at kotor_Randomizer_2.StartForm.LogCurrentSettings()
   at kotor_Randomizer_2.StartForm.randomize_button_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by LaneDibello** [comment]
The Exception thrown for Spoiler directory:
```
************** Exception Text **************
System.UnauthorizedAccessException: Access to the path 'C:\Program Files (x86)\Kotor Speedrun Community\Kotor Randomizer\Spoilers' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at System.IO.Directory.CreateDirectory(String path)
   at kotor_Randomizer_2.StartForm.openSpoilersFolderToolStripMenuItem_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by LaneDibello** [comment]
I've fixed the Xml folder issue with the installer. The fix is included in the InstallerFixes branch.

**Comment by LaneDibello** [comment]
I can confirm that the program works properly when installed to a directory with less access restrictions, such as a folder in documents. So it would appear the install location is the problem. We can either change the install location, or store the Spoiler logs and current.krp files in a more appropriate location (perhaps AppData). I also suppose we could just configure the randomizer to run as administrator. I would love to hear your opinion @glasnonck
